### ISSUE TITLE
How to self host

### ISSUE THREAD

**Issue by theforce1010** [LostLuma/starbin#1]
I tried to self host this but I am having hard time.
It would be a great help if there was a step by step guide

**Comment by LostLuma** [comment]
I can expand the readme to include all the steps once I am back at a computer soon.

You will need to fork this repo first (no need to edit any files if you don't want), then in the cloudflare dashboard under the workers tab create a KV namespace of any name you'd like, and then under the pages tab create a new pages project. On the creation screen you can link the KV namespace under the name described in the readme, as well as the other environment variables (they are all required I think).

Let me know if you can get it to work with these steps, else I can elaborate further, although it's difficult from a phone currently.

**Comment by theforce1010** [comment]
Thank you for the reply
I have done how you have said
but build is not working properly.. what will be the build command?
also i have set node variable to 16.7 as by default it was 12.x

**Comment by LostLuma** [comment]
Ah I forgot about that. You don't need a build command, so you can just put `echo Hello, World!` in the field. The build output directory is `/static/`.

**Comment by theforce1010** [comment]
Yes, that did the job
